checker:
  email_dir: emails
  proxies_dir: config/proxies.txt
  dead_emails_dir: out/dead.txt
  live_emails_dir: out/live.txt
  save_emails_dir: out/mail/
  edu_emails_dir: out/edu.txt
  log_level: 3
  max_workers: 40
  mode: loose # strict or loose
  search_terms:
    - edu
run_mode: tg # tg or local

push:
  type: bark  # 可以是bark pushplus serverchan
  token: xxxx

tg:
  api_id: 7286957268
  api_hash: AAE4ZcMO1xc7pEx20-8GWgWdocRfGU8eHRQ
  phone: +8613278858710 #手机号
  channel_list:
    - https://t.me/hotmailshare
  save_path: tg_emails
  my_channel: xxx  #无需配置
  forward_channel: https://t.me/lisenmail #无需配置
  check_interval: 28800
